version: 0.0
os: linux
files:
 -source: /
 destination: /home/ec2-user/node-express

 permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
 BeforeInstall:
   -location: scripts/application_install.sh
   runas: ec2-user
 ApplicationStart:
  -location: scripts/application_start.sh
  runas: ec2-user